#!/bin/bash

: ${NODE_PREFIX=amb}
: ${MYDOMAIN:=mycorp.kom}
: ${IMAGE:="sequenceiq/ambari:dns"}
: ${DOCKER_OPTS:="--dns 127.0.0.1 --entrypoint /bin/sh"}
: ${DEBUG:=1}

amb-clean() {
  unset NODE_PREFIX MYDOMAIN IMAGE DOCKER_OPTS DEBUG SERF_JOIN_IP
}

amb-members() {
  get-join-ip
  serf members --rpc-addr $(docker inspect --format "{{.NetworkSettings.IPAddress}}" ${NODE_PREFIX}0):7373
}
amb-settings() {
  cat <<EOF
  NODE_PREFIX=$NODE_PREFIX
  MYDOMAIN=$MYDOMAIN
  IMAGE=$IMAGE
  DOCKER_OPTS=$DOCKER_OPTS
  SERF_JOIN_IP=$SERF_JOIN_IP
EOF
}

debug() {
  [ -z $DEBUG ] || echo [DEBUG] $@
}

docker-ps() {
  #docker ps|sed "s/ \{3,\}/#/g"|cut -d '#' -f 1,2,7|sed "s/#/\t/g"
  docker inspect --format="{{.Name}} {{.NetworkSettings.IPAddress}} {{.Config.Image}} {{.Config.Entrypoint}} {{.Config.Cmd}}" $(docker ps -q)
}

docker-psa() {
  #docker ps|sed "s/ \{3,\}/#/g"|cut -d '#' -f 1,2,7|sed "s/#/\t/g"
  docker inspect --format="{{.Name}} {{.NetworkSettings.IPAddress}} {{.Config.Image}} {{.Config.Entrypoint}} {{.Config.Cmd}}" $(docker ps -qa)
}

get-join-ip() {
  : ${SERF_JOIN_IP:=$(docker inspect --format="{{.NetworkSettings.IPAddress}}" ${NODE_PREFIX}0)}
  # docker inspect --format="{{.Name}}" $(docker ps -q)|sed -n "/$NODE_PREFIX/ s:/${NODE_PREFIX}::p"
  debug SERF_JOIN_IP=$SERF_JOIN_IP
}

amb-start-first() {
  CMD="docker run -d $DOCKER_OPTS --name ${NODE_PREFIX}0 -h ${NODE_PREFIX}0.$MYDOMAIN $IMAGE -c /usr/local/serf/bin/start-serf-agent.sh --tag ambari-role=server,agent"
  debug $CMD
  $CMD
}

amb-start-node() {
  get-join-ip
  : ${SERF_JOIN_IP:?"SERF_JOIN_IP is needed"}
  NUMBER=${1:?"please give a <NUMBER> parameter it will be used as node<NUMBER>"}
  if [ $# -eq 1 ] ;then
    MORE_OPTIONS="-d"
  else
    shift
    MORE_OPTIONS="$@"
  fi
  CMD="docker run $MORE_OPTIONS -e SERF_JOIN_IP=$SERF_JOIN_IP $DOCKER_OPTS --name ${NODE_PREFIX}$NUMBER -h ${NODE_PREFIX}${NUMBER}.$MYDOMAIN $IMAGE -c /usr/local/serf/bin/start-serf-agent.sh"
  debug $CMD
  $CMD
}
