#!/bin/bash

: ${BRIDGE_IP:="172.17.42.1"}
: ${CONSUL_HTTP_PORT:="8500"}
: ${CLOUD_PLATFORM:="none"}

[[ "TRACE" ]] && set -x

debug() {
  [[ "DEBUG" ]]  && echo "[DEBUG] $@" 1>&2
}

# --dns isn't available for: docker run --net=host
# sed -i /etc/resolf.conf fails:
# sed: cannot rename /etc/sedU9oCRy: Device or resource busy
# here comes the tempfile workaround ...
fix-nameserver() {
  cat>/etc/resolv.conf<<EOF
nameserver $BRIDGE_IP
search service.consul node.consul
EOF
}

dig_ambari() {
  dig @$BRIDGE_IP ambari-8080.service.consul +short
}

set-server-ip() {
  while ! dig_ambari &>/dev/null || [ -z "$(dig_ambari)" ]; do
    sleep 1
    echo -n .
  done
  sed -i "s/^hostname=.*/hostname=$(dig_ambari)/" \
    /etc/ambari-agent/conf/ambari-agent.ini
}

# GCP overrides the /etc/hosts file with its internal hostname, so we need to change the
# order of the host resolution to try the DNS first
reorder_dns_lookup() {
  if [ "$CLOUD_PLATFORM" == "GCP" ] || [ "$CLOUD_PLATFORM" == "GCC" ]; then
    sed -i "/^hosts:/ s/ *files dns/ dns files/" /etc/nsswitch.conf
  fi
}

main() {
  fix-nameserver
  reorder_dns_lookup
  set-server-ip
  ambari-agent start -v
  /etc/init.d/sshd start
  while true; do
    sleep 3
    tail -f /var/log/ambari-agent/ambari-agent.log
  done
}

main "$@"
