#!/bin/bash

: ${BRIDGE_IP:="172.17.42.1"}
: ${CONSUL_HTTP_ADDR:="127.0.0.1:8500"}

[[ "TRACE" ]] && set -x

debug() {
  [[ "DEBUG" ]]  && echo "[DEBUG] $@" 1>&2
}

# --dns isn't available for: docker run --net=host
# sed -i /etc/resolf.conf fails:
# sed: cannot rename /etc/sedU9oCRy: Device or resource busy
# here comes the tempfile workaround ...
fix-nameserver() {
  cat>/etc/resolv.conf<<EOF
nameserver $BRIDGE_IP
search service.consul node.consul
EOF
}

dig_ambari() {
  dig @$BRIDGE_IP ambari-8080.service.consul +short
}

set-server-ip() {
  while [ -z "$(dig_ambari)" ]; do
    sleep 1
    echo -n .
  done
  sed -i "s/^hostname=.*/hostname=$(dig_ambari)/" \
    /etc/ambari-agent/conf/ambari-agent.ini
}

start-watch() {
  if [ -n "$CONSUL_HTTP_ADDR" ]; then
    consul watch --http-addr=$CONSUL_HTTP_ADDR --type=event /consul-event-handler.sh 2> /tmp/consul_handler.log &
  fi
}

main() {
  fix-nameserver
  set-server-ip
  ambari-agent start -v
  start-watch
  /etc/init.d/sshd start
  while true; do
    sleep 3
    tail -f /var/log/ambari-agent/ambari-agent.log
  done
}

main "$@"
