#!/bin/bash

[[ "TRACE" ]] && set -x

debug() {
  [[ "DEBUG" ]]  && echo "[DEBUG] $@" 1>&2
}

# --dns isn't available for: docker run --net=host
# sed -i /etc/resolf.conf fails:
# sed: cannot rename /etc/sedU9oCRy: Device or resource busy
# here comes the tempfile workaround ...
fix-nameserver() {
  local tmp=/tmp/resolv.con
  if grep -q 172.17.42.1 /etc/resolv.conf ;then
    debug [OK] /etc/resolv.conf
  else
    sed  "/search/ s/.*/search service.consul node.consul/; /nameserver/ i\nameserver 172.17.42.1" /etc/resolv.conf > $tmp
    cat $tmp > /etc/resolv.conf
  fi
}

dig_ambari() {
  dig @172.17.42.1 ambari-8080.service.consul +short
}

set-server-ip() {
  while [ -z "$(dig_ambari)" ]; do
    sleep 1
    echo -n .
  done
  sed -i "s/^hostname=.*/hostname=$(dig_ambari)/" \
    /etc/ambari-agent/conf/ambari-agent.ini
}

main() {
  fix-nameserver
  set-server-ip
  ambari-agent start -v
  /etc/init.d/sshd start
  while true; do
    sleep 3
    tail -f /var/log/ambari-agent/ambari-agent.log
  done
}

main "$@"
